### ISSUE TITLE
Jupyter kernel dying when running a 3x2pt forecast with A_s and m_nu

### ISSUE THREAD

**Issue by bruno-moraes** [LSSTDESC/augur#62]
When attempting a 3x2pt forecast with neutrino masses m_nu, it runs and completes when the sigma8 parameter is used. If A_s is used instead, the Jupyter kernel dies after a few seconds when trying to calculate the Fisher matrix.

I have not tested running from the command line nor with other parameter combinations. I will attempt to solve this by using A_s*10**9 instead of A_s.

**Comment by bruno-moraes** [comment]
I will work on this now.

**Comment by bruno-moraes** [comment]
@fjaviersanchez , I could pinpoint more or less where the error is, but this is something I never fixed before. I assume it's numerical instabilities in the derivatives due to the small values of A_s compared to the other parameters. I won't be able to solve it now.

**Comment by fjaviersanchez** [comment]
Thank you for checking and identifying the issue! I think this can be potentially solved when we add the stem derivative method. One potential solution is to normalize all parameters internally for the derivatives and then change back or change the step size dynamically, but will check first if the easy fix works.

**Comment by fjaviersanchez** [comment]
I included a way to normalize the parameters if you pass parameter bounds in the input configuration file (à la cosmosis) in #68. If you want to take a look at the latest master branch and retry. You will need to modify the `test.yaml` file changing `var_pars` to a `parameters` section that might look like:

```
fisher:
    # var_pars: ['Omega_c', 'sigma8', 'n_s', 'w0', 'wa', 'Omega_b', 'h', 'ia_bias', 'lens0_mag_bias', 'lens1_mag_bias', 'lens2_mag_bias', 'lens3_mag_bias', 'lens4_mag_bias', 'lens0_bias', 'lens1_bias', 'lens2_bias', 'lens3_bias', 'lens4_bias', 'src0_delta_z', 'src1_delta_z', 'src2_delta_z', 'src3_delta_z', 'src4_delta_z', 'lens0_delta_z', 'lens1_delta_z', 'lens2_delta_z', 'lens3_delta_z', 'lens4_delta_z']
    parameters:  # TODO: For now priors are ignored
         Omega_c: [0.06, 0.2664315, 0.46]
         sigma8: [0.03, 0.831, 1.2]
         n_s: [0.85, 0.9645, 1.10]
         w0: [-3.0, -1.0, -0.33]
         wa: [-3.0, 0.0, 3.0]
         Omega_b: [0.03, 0.0491685, 0.07]
         h: [0.5, 0.6727, 0.8]
        #  ia_bias: [-5.0, 1.0, 5.0]
        #  lens0_mag_bias: [-10, 0, 10]
        #  lens1_mag_bias: [-10, 0, 10]
        #  lens2_mag_bias: [-10, 0, 10]
        #  lens3_mag_bias: [-10, 0, 10]
        #  lens4_mag_bias: [-10, 0, 10]
        #  lens0_bias: [0.8, 1.23885511, 2.5]
        #  lens1_bias: [0.8, 1.3781005, 2.5]
        #  lens2_bias: [0.8, 1.52472019, 2.5]
        #  lens3_bias: [0.8, 1.67665752, 2.5]
        #  lens4_bias: [0.8, 1.83243479, 2.5]
        #  src0_delta_z: [-10, 0, 10]
        #  src1_delta_z: [-10, 0, 10]
        #  src2_delta_z: [-10, 0, 10]
        #  src3_delta_z: [-10, 0, 10]
        #  src4_delta_z: [-10, 0, 10]
        #  lens0_delta_z: [-10, 0, 10]
        #  lens1_delta_z: [-10, 0, 10]
        #  lens2_delta_z: [-10, 0, 10]
        #  lens3_delta_z: [-10, 0, 10]
        #  lens4_delta_z: [-10, 0, 10]
```
